baseURL = "https://ma-ket.github.io/"
languageCode = "ja-jp"
title = "Da-hama Site"
author = "Makoto Hamada"
theme = "github-style"
summarylength = 50
HasCJKLanguage = true
googleAnalytics = "G-XGGL1806HL"
paginate = 10
publishDir = "docs"  
contentDir = "content/post"
disableKinds = ["RSS", "sitemap"]

[Params]
Description = "だーはま"
Introduction = "いろんな知識を身につけて、快適な空間の中で人生を送りたい。"
dateformat = "2022/4/12"

[taxonomies]
tag = "tags"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]
enableGitInfo = true
