baseURL = 'https://ma-ket.github.io/'
languageCode = 'ja'
title = 'Da-hama Site'
theme = 'github-style'
publishDir = "docs"  
contentDir = "content/post"
disableKinds = ["RSS", "sitemap"]
[taxonomies]
tag = "tags"
